# Generated by Django 2.2 on 2019-04-18 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Thread Title')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tag Name')),
                ('description', models.TextField(verbose_name='Tag Description')),
                ('posts', models.ManyToManyField(to='forum.Thread')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField(verbose_name='Post Contents')),
                ('pub_date', models.DateTimeField(verbose_name='Date Published')),
                ('parent_thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='forum.Thread')),
                ('reply_target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', related_query_name='reply', to='forum.Post')),
            ],
        ),
    ]
