# Generated by Django 2.2 on 2019-04-25 19:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20190420_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 25, 15, 17, 14, 61627), verbose_name='Date Published'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forumuser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_user', related_query_name='forum_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
